/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import dominio.controlador.Ctrl_diputat;
import java.util.HashSet;
import java.util.Set;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import dominio.Data;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import persistencia.FileManager;
import presentacion.controlador.Ctrl_VistaEvent;
import presentacion.controlador.Ctrl_VistaParlament;

/**
 *
 * @author adrian
 */
public class VistaEvent extends javax.swing.JFrame {

    /**
     * Creates new form VistaEvent
     */
    private Set<String> events;
    private int NumRow;
    private Afegir_Event Ae = new Afegir_Event(this, true);
    private Modifica_basic_event Me = new Modifica_basic_event(this, true);
    private Ctrl_VistaEvent cVE;
    
    public VistaEvent() {
        events = new HashSet<>();
        initComponents();
    }
    
    public void creaControladors(Ctrl_VistaParlament instancia) {
        cVE = new Ctrl_VistaEvent(this, instancia);
    }
    
    public Ctrl_VistaEvent getCtrl_VistaEvent() {
        return cVE;
    }
    
    private int TipusToInt(String tipus) {
        /* tipusEvent = {0,1,2,3,4} equivalent a {reunio, esport, votacio, dinar, conferencia}.*/
        if (tipus.equals("Reunio")) return 0;
        else if (tipus.equals("Esport")) return 1;
        else if (tipus.equals("Votacio")) return 2;
        else if (tipus.equals("Dinar")) return 3;
        else if (tipus.equals("Conferencia")) return 4;
        return -1; // cas d'error, mai es pot donar
    }
    
    
    // tambe serveix per a actualitzar
    protected void modificarEvent(Vector<String> info) {
        // llamar a los controladores pertinentes, actualizar la tabla
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        model.removeRow(NumRow);
        model.insertRow(NumRow, info);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CreaEvent = new javax.swing.JButton();
        AssociaDiputats = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Tipus", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        CreaEvent.setText("CREA EVENT");
        CreaEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreaEventActionPerformed(evt);
            }
        });

        AssociaDiputats.setText("ASSOCIA DIPUTATS");
        AssociaDiputats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssociaDiputatsActionPerformed(evt);
            }
        });

        jButton1.setText("CONSULTA ASSOCIATS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ESBORRA EVENT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("GUARDA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CARREGA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("DESASSOCIA DIPUTATS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setText("solamente para prueba");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(2, 2, 2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AssociaDiputats, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreaEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addGap(0, 49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreaEvent)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(AssociaDiputats)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        public void afegir_dades_taula(Vector<String> info) {
        if (events.contains(info.get(0))) {
            Missatge_basic mb = new Missatge_basic(this, true);
            mb.setMsg("Event a existeix");
            mb.setVisible(true);
            mb.pack();
        }
        else {
            DefaultTableModel model;
            model = (DefaultTableModel) jTable1.getModel();
            model.addRow(info);
            events.add(info.firstElement());
        }
       
    }
     
    private void CreaEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreaEventActionPerformed
        // TODO add your handling code here:
        NumRow = jTable1.getRowCount();
        Ae.AsociarVistaEvent(this);
        Ae.setVisible(true);
        Ae.pack();
        
        
    }//GEN-LAST:event_CreaEventActionPerformed
    
    private int getRowSel() {
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        int[] selectedRows = jTable1.getSelectedRows();
        if (selectedRows.length == 1) {
            return selectedRows[0];
        }
        else {
            Missatge_basic msg = new Missatge_basic(this, true);
            msg.setMsg("Selecciona una fila");
            msg.setVisible(true);
            msg.pack();
        }
        return -1;
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // esto es visualizar los asociados
        int r = getRowSel();
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        String nomEv = (String) jTable1.getModel().getValueAt(r, 0);
        if (((String)model.getValueAt(r, 1)).equals("Votacio")) {
            TaulaDip t = new TaulaDip(this, true);
            System.out.println("Soy una votacion");
            if (cVE.consultaAssociatsVotacio(nomEv) == null) {
                System.out.println("Porque??");
            }
            System.out.println(cVE.consultaAssociatsVotacio(nomEv));
            t.carrega_dades_taula(cVE.consultaAssociatsVotacio(nomEv));
            t.setVisible(true);
            t.pack();
        }
        else {
            TaulaDip t = new TaulaDip(this, true);
            t.carrega_dades_taula(cVE.consultaAssociats(nomEv));
            t.setVisible(true);
            t.pack();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        cVE.guarda_events_fitxer("F:/PROP/eventos");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        cVE.carrega_events_fitxer("F:/PROP/eventos");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void AssociaDiputatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssociaDiputatsActionPerformed
        // TODO add your handling code here:
        int r = getRowSel();
        String nomEv = (String) jTable1.getModel().getValueAt(r, 0);
        String tipus = (String) jTable1.getModel().getValueAt(r, 1);
        if (!tipus.equals("Votacio")) { // no es una votacion
            System.out.println(r);
            TaulaEvAss tEvA = new TaulaEvAss(this, true);
            tEvA.associar_Ctrl_VistaEvent(cVE, nomEv);
            tEvA.carrega_dades_taula(cVE.consultaPotencialsAssociar(nomEv));
            tEvA.setVisible(true);
            tEvA.pack();
        }
        else {
            if (cVE.permetAssignarVotacio(nomEv)) {
                TaulaVotacions  tV = new TaulaVotacions(this, true);
                tV.associar_Ctrl_VistaEvent(cVE, nomEv);
                tV.carrega_dades_taula(cVE.consultaPotencialsAssociar(nomEv));
                tV.setVisible(true);
                tV.pack();
            }
            else {
                Missatge_basic_errors m = new Missatge_basic_errors(this, true);
                m.append_error("Aquesta votacio ja s'ha produit");
                m.setVisible(true);
                m.pack();
            }
            
            
        }
        
    }//GEN-LAST:event_AssociaDiputatsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int r = getRowSel();
        String nomEv = (String) jTable1.getModel().getValueAt(r, 0);
        DefaultTableModel model;
        model = (DefaultTableModel) jTable1.getModel();
        if (!((String)jTable1.getModel().getValueAt(r, 1)).equals("Votacio")) {
            cVE.eliminaEvent(nomEv);
        }
        else {
            cVE.eliminaEventVotacio(nomEv);
        }
        Missatge_basic mb = new Missatge_basic(this, true);
        model.removeRow(r);
        mb.setMsg("Event eliminat correctament");
        mb.setVisible(true);
        mb.pack();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int r = getRowSel();
        String nomEv = (String) jTable1.getModel().getValueAt(r, 0);
        TaulaEvDesAss t = new TaulaEvDesAss(this, true);
        t.associar_Ctrl_VistaEvent(cVE, nomEv);
        t.carrega_dades_taula(cVE.consultaAssociats(nomEv));
        t.setVisible(true);
        t.pack();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssociaDiputats;
    private javax.swing.JButton CreaEvent;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
