/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.DefaultListModel;
import java.util.*;
import javax.swing.JOptionPane;
import presentacion.controlador.*;
/**
 *
 * @author David
 */
public class vistaparesolucio extends javax.swing.JFrame {
    private ctrlvistaSol ct = new ctrlvistaSol();
    private DefaultListModel sols = new DefaultListModel();
    private String plantilla = "1";
    private String Alg = "Louvain";
    private Set<String> ids = new HashSet<String>();
    private String idsel;
    private String sol = "0";
    private static Ctrl_VistaParlament d;
    /**
     * Creates new form vistaparesolucio
     */
    public vistaparesolucio(Ctrl_VistaParlament d) {
        initComponents();
        initMyComponents();
        listSolucions.setModel(sols);
        this.d=d;
    }
    
    private void initMyComponents(){
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listSolucions = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        btGenera = new javax.swing.JButton();
        btElimina = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(listSolucions);

        jLabel1.setText("Solucions");

        btGenera.setText("Genera Solucio");
        btGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeneraActionPerformed(evt);
            }
        });

        btElimina.setText("Elimina Solucio");
        btElimina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminaActionPerformed(evt);
            }
        });

        btConsulta.setText("Consulta Solucio");
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btElimina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGenera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGenera)
                .addGap(49, 49, 49)
                .addComponent(btElimina)
                .addGap(48, 48, 48)
                .addComponent(btConsulta)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeneraActionPerformed
        this.setVisible(false);
        new vistageneraSol(this,true,this.sol, this.ids).setVisible(true);
    }//GEN-LAST:event_btGeneraActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        int i = this.listSolucions.getSelectedIndex();
        if(i >= 0){
            ct.setId(this.listSolucions.getSelectedValue().toString());
            this.setVisible(false);
            new ctvistaconSol(this).setVisible(true);
        }
        else JOptionPane.showMessageDialog(this, "selecciona un element");
    }//GEN-LAST:event_btConsultaActionPerformed

    private void btEliminaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminaActionPerformed
        int i = this.listSolucions.getSelectedIndex();
        if(i >= 0){
            if(! ct.eliminaSolucio(this.listSolucions.getSelectedValue().toString())) JOptionPane.showMessageDialog(this, "error eliminant solucio");
            else sols.remove(i);
        }
        else JOptionPane.showMessageDialog(this, "selecciona una solucio");
    }//GEN-LAST:event_btEliminaActionPerformed

    
    public String getPlantilla(){
        return plantilla;
    }
    
    public void setPlantilla(String Plantilla){
        this.plantilla = plantilla;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaparesolucio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaparesolucio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaparesolucio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaparesolucio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaparesolucio(d).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btElimina;
    private javax.swing.JButton btGenera;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listSolucions;
    // End of variables declaration//GEN-END:variables

    public String getAlg() {
        return Alg;
    }
    
    public void setAlg(String Alg){
        this.Alg = Alg;
    }
    
    public ctrlvistaSol getctrl(){
        return ct;
    }
    
    public void mant(Set<String> ids){
        System.out.print("ids: ");
        System.out.println(ids);
        for(String s : ids){
            System.out.println("afegeixo " + s);
            sols.addElement(s);
        }
    }
    
    public boolean addSol(String st){
        if(ids.contains(st)) return false;
        else{
            sols.addElement(st);
            ids.add(st);
            System.out.println(ids);
            return true;
        }
    }
    
    void setSol(String sol){
        this.sol = sol;
    }

    String selected() {
        return idsel;
    }

    void setids(Set<String> ids) {
        this.ids = ids;
    }
}
