/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.JOptionPane;
import java.util.*;
import presentacion.controlador.ctrlvistaSol;

/**
 *
 * @author David
 */
public class vistageneraSol extends javax.swing.JDialog {
    private vistaparesolucio pare;
    private ctrlvistaSol ct;
    private Set<String> ids;
    String id;
    boolean mod = false;
    /**
     * Creates new form vistageneraSol
     */
    public vistageneraSol(java.awt.Frame parent, boolean modal, String id, Set<String> ids) {
        super(parent, modal);
        initComponents();
        pare = (vistaparesolucio)parent;
        this.tfAlgorisme.setText(pare.getAlg());
        this.tfPlantillaActual.setText(pare.getPlantilla());
        ct = pare.getctrl();
        this.id = id;
        this.jlid.setText(id.toString());
        this.ids = ids;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btPlantilla = new javax.swing.JButton();
        cbAlgorisme = new javax.swing.JComboBox();
        btConfirmar = new javax.swing.JButton();
        btCancela = new javax.swing.JButton();
        tfPlantillaActual = new javax.swing.JTextField();
        tfAlgorisme = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btPlantilla.setText("Seleccio Plantilla");
        btPlantilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlantillaActionPerformed(evt);
            }
        });

        cbAlgorisme.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Algorisme", "Louvain", "Clique", "Girvan Newman" }));
        cbAlgorisme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAlgorismeActionPerformed(evt);
            }
        });

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        btCancela.setText("Cancela");
        btCancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelaActionPerformed(evt);
            }
        });

        tfPlantillaActual.setEditable(false);
        tfPlantillaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPlantillaActualActionPerformed(evt);
            }
        });

        tfAlgorisme.setEditable(false);
        tfAlgorisme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAlgorismeActionPerformed(evt);
            }
        });

        jLabel1.setText("Plantilla Actual");

        jLabel2.setText("Algorisme Actual");

        jLabel4.setText("Solucio");

        jlid.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPlantillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlgorisme, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btConfirmar)
                        .addGap(55, 55, 55)
                        .addComponent(btCancela))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbAlgorisme, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btPlantilla, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jlid)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jlid))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfPlantillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPlantilla))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfAlgorisme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAlgorisme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btConfirmar)
                    .addComponent(btCancela))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelaActionPerformed
        this.tfAlgorisme.setText("");
        this.tfPlantillaActual.setText("");
        pare.setSol(this.id);
        pare.setAlg(this.tfAlgorisme.getText());
        pare.setPlantilla(this.tfPlantillaActual.getText());
        pare.setids(this.ids);
        this.setVisible(false);
        pare.setVisible(true);
    }//GEN-LAST:event_btCancelaActionPerformed

    private void tfAlgorismeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAlgorismeActionPerformed

    }//GEN-LAST:event_tfAlgorismeActionPerformed

    private void tfPlantillaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPlantillaActualActionPerformed
        
    }//GEN-LAST:event_tfPlantillaActualActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
        try{    
            if(this.id.equals("")) JOptionPane.showMessageDialog(this, "has de seleccionar una Id");
            else{
                if(ct.generaSolucio(this.id, this.tfAlgorisme.getText(), this.tfPlantillaActual.getText())){
                    Integer id = Integer.valueOf(this.id);
                    if(! mod){
                        mod = true;
                    }
                    if(! pare.addSol(this.id)) JOptionPane.showMessageDialog(this, "la solucio ja existeix");
                    else ids.add(this.id);
                    id++;
                    this.id = id.toString();
                    jlid.setText(this.id);
                }
                else JOptionPane.showMessageDialog(this, "error en generar solucio");
            }
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "la id ha de ser un numero");
        }
    }//GEN-LAST:event_btConfirmarActionPerformed

    private void cbAlgorismeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAlgorismeActionPerformed
        if(this.cbAlgorisme.getSelectedIndex() != 0){
            pare.setAlg(this.cbAlgorisme.getSelectedItem().toString());
            this.tfAlgorisme.setText(this.cbAlgorisme.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbAlgorismeActionPerformed

    private void btPlantillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlantillaActionPerformed
        this.setVisible(false);
        new Vistasolplant(this).setVisible(true);
    }//GEN-LAST:event_btPlantillaActionPerformed

    
    void estableixPlantilla(String pl){
        this.tfPlantillaActual.setText(pl);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistageneraSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistageneraSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistageneraSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistageneraSol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistageneraSol dialog = new vistageneraSol(new javax.swing.JFrame(), true, "0", null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancela;
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton btPlantilla;
    private javax.swing.JComboBox cbAlgorisme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jlid;
    private javax.swing.JTextField tfAlgorisme;
    private javax.swing.JTextField tfPlantillaActual;
    // End of variables declaration//GEN-END:variables
}
